### ISSUE TITLE
Lottery ticket not generating

### ISSUE THREAD

**Issue by luciouscake** [Martinsmith67/lottery#2]
ticket did not generate after running the action. when is the ticket purchased and numbers generated

**Comment by Martinsmith67** [comment]
Did you put in cake and BNB wait for both transactions to complete then run the action?

**Comment by luciouscake** [comment]
yes i did and waited for the lottery to run and no ticket generated

**Comment by Martinsmith67** [comment]
No you have to wait for both transactions to complete before running the action. Cakes take longer to send best bet is to send the BNB and cake to the contract and wait a good 20 minutes before running the action

**Comment by luciouscake** [comment]
i did that and still nothing :/

**Comment by Martinsmith67** [comment]
Ok I just tried and it's working . What day did you try? I will look at the blockchain ,To try analyze what happened
